# Generated by Django 3.2 on 2022-04-29 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='late_entry',
        ),
        migrations.AddField(
            model_name='lateentry',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='late_entry', to='Core.student'),
            preserve_default=False,
        ),
    ]
