# Generated by Django 4.0.4 on 2022-05-01 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_student_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Venues',
            },
        ),
        migrations.AddField(
            model_name='lateentry',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_entry', to='Core.venue'),
        ),
    ]
