# Generated by Django 4.0.4 on 2022-05-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
        ('Core', '0004_venue_lateentry_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Auth.user',),
        ),
    ]
