# Generated by Django 4.0.4 on 2022-05-02 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={},
        ),
    ]
