# Generated by Django 4.0.4 on 2022-05-06 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_alter_venue_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lateentry',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_entry', to='Core.venue'),
        ),
    ]
