# Generated by Django 4.0.4 on 2022-05-11 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_alter_lateentry_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['batch'],
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(check=models.Q(('batch__gt', 1998)), name='check_batch'),
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batch'),
        ),
    ]
