# Generated by Django 4.0.4 on 2022-05-10 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_alter_lateentry_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lateentry',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='late_entry', to='Core.venue'),
        ),
    ]
