# Generated by Django 4.0.4 on 2022-05-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_batch_remove_student_year_delete_year_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='batch',
            name='check_batch',
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(check=models.Q(('batch__gt', 1997)), name='check_batch'),
        ),
    ]
