# Generated by Django 4.0.4 on 2022-05-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_alter_lateentry_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
