# Generated by Django 4.0.4 on 2022-05-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_remove_batch_check_batch_batch_check_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lateentry',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
