# Generated by Django 4.0.4 on 2022-05-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_venue_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='st_no',
            new_name='student_no',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
