# Generated by Django 4.0.4 on 2022-05-15 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_rename_st_no_student_student_no_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9A-Z]{1,11}$')]),
        ),
    ]
