# Generated by Django 4.0.4 on 2022-05-12 17:18

import Core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_alter_lateentry_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='picture',
        ),
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Core.models.StudentImage.get_image_path)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.batch')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.student')),
            ],
        ),
    ]
