# Generated by Django 4.0.4 on 2022-05-15 08:32

import Core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_alter_student_student_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[Core.validators.student_no_re]),
        ),
    ]
