# Generated by Django 4.0.4 on 2022-05-12 19:36

import Core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_remove_student_picture_studentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentimage',
            name='image',
            field=models.FileField(upload_to=Core.models.StudentImage.get_image_path),
        ),
    ]
