# Generated by Django 4.0.4 on 2022-05-13 13:43

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0016_alter_clipboard_id_alter_clipboarditem_id_and_more'),
        ('Core', '0012_alter_studentimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentimage',
            name='image',
        ),
        migrations.AddField(
            model_name='studentimage',
            name='img',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.file'),
        ),
    ]
