# Generated by Django 4.0.4 on 2022-05-15 10:26

import Core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_alter_student_student_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.IntegerField(null=True, validators=[Core.validators.branch_code_re()]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=50, validators=[Core.validators.branch_name_re()]),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, validators=[Core.validators.student_name_re()]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue',
            field=models.CharField(max_length=20, validators=[Core.validators.branch_name_re()]),
        ),
    ]
