# Generated by Django 4.0.4 on 2022-05-15 10:34

import Core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_alter_branch_code_alter_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.IntegerField(validators=[Core.validators.branch_code_re()]),
        ),
    ]
