# Generated by Django 4.0.4 on 2022-05-17 13:39

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_customimage_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentimage',
            name='img',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
