# Generated by Django 4.0.4 on 2022-05-17 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0016_alter_clipboard_id_alter_clipboarditem_id_and_more'),
        ('Core', '0016_alter_studentimage_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilerAdmin',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filer.file')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('filer.file',),
        ),
    ]
