# Generated by Django 4.0.4 on 2022-05-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0017_fileradmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileradmin',
            options={'base_manager_name': 'objects'},
        ),
    ]
