# Generated by Django 4.0.4 on 2022-05-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_alter_fileradmin_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomImage',
        ),
    ]
