# Generated by Django 4.0.4 on 2022-05-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0020_customimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomImage',
        ),
    ]
