# Generated by Django 4.0.4 on 2022-05-18 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_customimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.batch'),
        ),
    ]
