# Generated by Django 4.0.4 on 2022-05-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0023_customimage_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.branch'),
        ),
    ]
